### ISSUE TITLE
Create DB Sceme

### ISSUE THREAD

**Issue by venmer** [nonironman/flotski#1]

**Comment by Bright-Head** [comment]
Database schema has been added to repo. Need to be reviewed and approved.

**Comment by venmer** [comment]
was decided to add `user_id` FK field to Guest and Booking tables. `state` field will be removed from Room table, actual room state depends on current booking.
Booking table will be extended with an optional field - `description`

**Comment by Bright-Head** [comment]
Add `state` to User instance as active/inactive indicator.

**Comment by venmer** [comment]
implemented under #10

**Comment by Bright-Head** [comment]
@venmer, I think that room can't be permanently deleted as well as user, and room should have `state` for active/inactive state. What do you think?
Also in case `state`=inactive, room is unavailable for booking creation.

**Comment by venmer** [comment]
@Bright-Head, agreed. Room table will be extended with `state=(active,inactive)` as well.

**Comment by venmer** [comment]
@Bright-Head, please correct relations between `GuestToBooking` and `Guest` entities
